### ISSUE TITLE
Issues when accessing link

### ISSUE THREAD

**Issue by b101marc** [LukeChannings/moviematch#6]
Hi there,

I have this installed via Docker and behind Traefik and am able to access my domain just fine to pull up MovieMatch, however I'm experiencing the two following issues:

1. When accessing via Desktop the GENERATE button does nothing, but ENGAGE works but loads an error page.
2. When accessing via mobile the ENGAGE button does nothing, but GENERATE creates a code for a room.

Any guidance appreciated.

**Comment by LukeChannings** [comment]
This could be caused by #4. Can you try pulling the latest image?

**Comment by b101marc** [comment]
Hey there,

I did as instructed and had docker pull the latest image and am getting the following output: 

`Check file:///app/src/index.ts
error: TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'. 'Deno.signal' is an unstable API. Did you forget to run with the '--unstable' flag?
Deno.signal(Deno.Signal.SIGINT).then(() => {
     ~~~~~~
    at file:///app/src/index.ts:17:6

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?

Deno.signal(Deno.Signal.SIGINT).then(() => {
                 ~~~~~~
   at file:///app/src/index.ts:17:18=
Found 2 errors.`

Any suggestions?

**Comment by LukeChannings** [comment]
Sorry, I've fixed that now. Pull one more time?

**Comment by b101marc** [comment]
Same error after pulling with :latest tag via docker

**Comment by LukeChannings** [comment]
I'm not entirely sure why `:latest` wouldn't have fixed it for your to be honest.

I've just pushed [v1.2.0](https://github.com/LukeChannings/moviematch/releases/tag/v1.2.0) with a some bugfixes.
Can you try using the 1.2.0 image?

**Comment by b101marc** [comment]
Hmm. When using lukechannings/moviematch:v1.2.0 I got an error with no version matches.

**Comment by b101marc** [comment]
Tried using latest yeah and got it working. Takes a very long time to load movies, nothing loaded as of yet.

**Comment by LukeChannings** [comment]
It's `lukechannings/moviematch:1.2.0`, no v before the version in Docked. 

https://hub.docker.com/layers/129568354/lukechannings/moviematch/1.2.0/images/sha256-3805abea5f7e473f35607fcce038586f1f79225e2da5e9167fba51cd65ec3044?context=explore

**Comment by LukeChannings** [comment]
> Tried using latest yeah and got it working. Takes a very long time to load movies, nothing loaded as of yet.

How many movies are in your collection? It takes < 100ms to load 1000 movies on my server.

**Comment by b101marc** [comment]
Just under 10k

**Comment by LukeChannings** [comment]
All in one library?

I might add some instrumentation to see what's taking the time. Once it loads the library it caches it, so it'll only take time when it starts up. 

Is the Plex web UI usable for you with that many movies?

**Comment by b101marc** [comment]
Yeah I've never had an issue. I'll turn up the log level and see what shakes out.

**Comment by b101marc** [comment]
Turned logs to DEBUG and received the following:
`INFO Listening on port 8000
DEBUG serveFile(/app/public/index.html)
DEBUG serveFile(/app/public/main.js)
DEBUG serveFile(/app/public/logo.svg)
DEBUG serveFile(/app/public/style.css)
DEBUG serveFile(/app/public/MovieMatchAPI.js)
DEBUG serveFile(/app/public/MatchesView.js)
DEBUG serveFile(/app/public/CardView.js)
DEBUG serveFile(/app/public/background.svg)
DEBUG serveFile(/app/public/background-grain.png)
INFO Got a login: {"name":"Brayden","roomCode":"65WN"}
DEBUG New session created. Active session ids are: 65WN
DEBUG New user Brayden logged in
DEBUG Brayden asked for the next batch of movies`

It has been about 5 minutes, no change.

**Comment by b101marc** [comment]
I was able to get it working. User error on my behalf, my Plex URL was in the incorrect format for a secure connection.

**Comment by LukeChannings** [comment]
What format did you use? I'll update it to time out and give an error in the future.
